name: Run Tests and Comment on PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test-and-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Tests
        id: tests
        run: |
          npm ci
          echo "test_results<<EOF" >> $GITHUB_OUTPUT
          npm test 2>&1 | tee test_output.txt || echo "Tests failed with exit code $?"
          cat test_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR with Test Results
        if: ${{ always() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Test Results

            ```
            ${{ steps.tests.outputs.test_results }}
            ```
