name: Run Tests and Comment on PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test-and-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Tests
        id: tests
        continue-on-error: true
        run: |
          npm ci
          npm test 2>&1 | tee test-output.log

      - name: Comment PR with Test Results
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: test-output.log
